config/routes.rb
Rails.application.routes.draw do
  get 'sales/list'
  resources :sales
  resources :items
  root 'sales#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales/list
  def list
      @sales = Sale.all
      @total_price = 0
      @total_sum = 0
      @total_tax = 0
      @sales.each do |sale|
        @total_sum += (sale.price * sale.item.price).to_i
        @total_tax += (sale.price * sale.item.price * 0.08).to_i
        @total_price += (sale.price * sale.item.price * 1.08).to_i
      end
  end

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:date, :item_id, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :商品名 %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :価格 %>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>編集</h1>

<%= render 'form', item: @item %>

<%= link_to '詳細', @item %> |
<%= link_to '戻る', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>商品一覧</h1>

<table>
  <thead>
    <tr>
      <th>商品名</th>
      <th>価格</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= link_to '詳細', item %></td>
        <td><%= link_to '編集', edit_item_path(item) %></td>
        <td><%= link_to '削除', item, method: :delete, data: { confirm: '削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規登録', new_item_path %> |
<%= link_to '売上一覧', controller: :sales, action: :index %>

app/views/items/new.html.erb
<h1>新規登録</h1>

<%= render 'form', item: @item %>

<%= link_to '戻る', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>商品名:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>価格:</strong>
  <%= @item.price %>
</p>

<%= link_to '編集', edit_item_path(@item) %> |
<%= link_to '戻る', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Starbucks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/_form.html.erb
<%= form_for(sale) do |f| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :日付 %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :商品名 %>
    <%= f.collection_select(:item_id, Item.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :個数 %>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>編集</h1>

<%= render 'form', sale: @sale %>

<%= link_to '詳細', @sale %> |
<%= link_to '戻る', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>売上一覧</h1>

<table>
  <thead>
    <tr>
      <th>日付</th>
      <th>商品名</th>
      <th>単価</th>
      <th>個数</th>
      <th>消費税</th>
      <th>合計</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.date %></td>
        <td><%= sale.item.name %></td>
        <td><%= sale.item.price %></td>
        <td><%= sale.price %></td>
        <td><%= (sale.price * sale.item.price * 0.08).to_i %></td>
        <td><%= (sale.price * sale.item.price * 1.08).to_i %></td>
        <td><%= link_to '詳細', sale %></td>
        <td><%= link_to '編集', edit_sale_path(sale) %></td>
        <td><%= link_to '削除', sale, method: :delete, data: { confirm: '削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to '新規登録', new_sale_path %> |
<%= link_to '商品一覧', controller: :items, action: :index %> |
<%= link_to '売上集計', controller: :sales, action: :list %>

app/views/sales/list.html.erb
<p id="notice"><%= notice %></p>

<h1>売上集計</h1>

<table>
  <thead>
    <tr>
      <th>日付</th>
      <th>商品名</th>
      <th>単価</th>
      <th>個数</th>
      <th>消費税</th>
      <th>合計</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.date %></td>
        <td><%= sale.item.name %></td>
        <td><%= sale.item.price %></td>
        <td><%= sale.price %></td>
        <td><%= (sale.price * sale.item.price * 0.08).to_i %></td>
        <td><%= (sale.price * sale.item.price * 1.08).to_i %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  小計：<%= @total_sum %>円<br>
  外税：<%= @total_tax %>円<br>
  合計：<%= @total_price %>円<br>
<br>
<%= link_to '売上一覧', controller: :sales, action: :index %>

app/views/sales/new.html.erb
<h1>新規登録</h1>

<%= render 'form', sale: @sale %>

<%= link_to '戻る', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>日付:</strong>
  <%= @sale.date %>
</p>

<p>
  <strong>商品名:</strong>
  <%= @sale.item.name %>
</p>

<p>
  <strong>個数:</strong>
  <%= @sale.price %>
</p>

<%= link_to '編集', edit_sale_path(@sale) %> |
<%= link_to '戻る', sales_path %>